project_name: cloudcompare-tui

builds:
    - id: cloudcompare-tui
      main: ./cmd/cloudcompare-tui
      binary: cloudcompare-tui
      env:
          - CGO_ENABLED=0
      goos:
          - linux
          - darwin
          - windows
      goarch:
          - amd64
          - arm64
      ldflags:
          - -s -w

archives:
    - id: release-archive
      builds:
          - cloudcompare-tui
      format: tar.gz
      format_overrides:
          - goos: windows
            format: zip
      name_template: >-
          {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
      files:
          - LICENSE
          - README.md

checksum:
    name_template: "checksums.txt"

snapshot:
    name_template: "{{ .Tag }}-next"

changelog:
    use: github
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"
